#cloud:
#  aws:
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY}
#      secretKey: ${AWS_SECRET_KEY}
#    s3:
#      bucket: cozystates-bucket-01
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: 'false'
#spring:
#  datasource:
#    url: jdbc:mysql://database-cozystates.c1hypxzbotyv.ap-northeast-2.rds.amazonaws.com:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: admin
#    password: 12341234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true  # (3) SQL pretty print
#    servlet:
#      multipart:
#        max-file-size: 10MB
#        max-request-size: 10MB
#    sql:
#      init:
#        data-locations: classpath*:db/h2/data.sql
#  logging:
#    level:
#      org:
#        springframework:
#          orm:
#            jpa: DEBUG
#config:
#  domain: http://cozystates-bucket-01.s3-website.ap-northeast-2.amazonaws.com
#
