INSERT INTO theme (title) VALUES ('A');
INSERT INTO theme (title) VALUES ('B');
INSERT INTO theme (title) VALUES ('C');
INSERT INTO theme (title) VALUES ('D');
INSERT INTO theme (title) VALUES ('E');

INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('b',null,2);
INSERT INTO content (title, uri, theme_id) VALUES ('b',null,2);
INSERT INTO content (title, uri, theme_id) VALUES ('c',null,3);
INSERT INTO content (title, uri, theme_id) VALUES ('c',null,3);
INSERT INTO content (title, uri, theme_id) VALUES ('c',null,3);
INSERT INTO content (title, uri, theme_id) VALUES ('d',null,4);
INSERT INTO content (title, uri, theme_id) VALUES ('d',null,4);
INSERT INTO content (title, uri, theme_id) VALUES ('d',null,4);
INSERT INTO content (title, uri, theme_id) VALUES ('d',null,4);
INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);
INSERT INTO content (title, uri, theme_id) VALUES ('a',null,1);

INSERT INTO member (email, password, active, username, role) VALUES ("admin@adadad.com", "sksmsdurlwndlsektzzz123", true, "admin", "ADMIN");