INSERT INTO theme (title) VALUES ('Nature');
INSERT INTO theme (title) VALUES ('Space');
INSERT INTO theme (title) VALUES ('Retro');
INSERT INTO theme (title) VALUES ('Pixel Art');
INSERT INTO theme (title) VALUES ('Animal');

INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-1.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('b',null,2);
INSERT INTO content (title, uri, theme_id) VALUES ('b',null,2);
INSERT INTO content (title, uri, theme_id) VALUES ('c',null,3);
INSERT INTO content (title, uri, theme_id) VALUES ('c',null,3);

INSERT INTO content (title, uri, theme_id) VALUES ('c',null,3);
INSERT INTO content (title, uri, theme_id) VALUES ('d',null,4);
INSERT INTO content (title, uri, theme_id) VALUES ('d',null,4);
INSERT INTO content (title, uri, theme_id) VALUES ('d',null,4);
INSERT INTO content (title, uri, theme_id) VALUES ('d',null,4);

INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('Cat',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);
INSERT INTO content (title, uri, theme_id) VALUES ('e',null,5);

INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-16.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-17.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-18.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-19.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-20.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-21.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-22.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-23.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-24.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-25.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-26.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-27.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-28.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-29.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-30.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-31.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-32.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-33.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-34.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-35.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-36.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-37.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-38.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-39.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-40.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-41.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-42.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-43.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-44.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-45.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-46.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-47.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-48.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-49.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-50.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-51.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-52.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-53.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-54.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-55.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-56.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-57.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-58.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-59.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-60.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-61.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-62.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-63.jpg',1);
INSERT INTO content (title, uri, theme_id) VALUES ('a','https://29testmain.s3.ap-northeast-2.amazonaws.com/1-64.jpg',1);